version: "2"
services:
  api:
    image: quizzendirect-dev/quizzapi:latest
    ports:
     - 20020:20020
  frontapp:
    image: quizzendirect-dev/qed:latest
    ports:
     - 8081:8081
  proxy:
    image: nginx
    volumes:
      - ./conf.d/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./conf.d/nginx/proxy_params:/etc/nginx/proxy_params

    ports: 
      - 80:80

